version: 1.2
workflows:
  - name: assembly_qc
    subclass: WDL
    primaryDescriptorPath: /Workflows/CAMRA_QC_WF.wdl
    authors:
      - name: Daniella Matute
        email: dmatute@jcvi.org
  - name: genome_assembly
    subclass: WDL
    primaryDescriptorPath: /Workflows/CAMRA_ASM_WF.wdl
    authors:
      - name: Andrew LaPointe
        email: andrewrlapointe@gmail.com
