#!/bin/bash

cd /cromwell-executions/assembly_qc/78339930-ab3d-4f8d-b9a3-c4f42da3fab6/call-run_fastQC/execution
tmpDir=$(mkdir -p "/cromwell-executions/assembly_qc/78339930-ab3d-4f8d-b9a3-c4f42da3fab6/call-run_fastQC/tmp.2d573071" && echo "/cromwell-executions/assembly_qc/78339930-ab3d-4f8d-b9a3-c4f42da3fab6/call-run_fastQC/tmp.2d573071")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/assembly_qc/78339930-ab3d-4f8d-b9a3-c4f42da3fab6/call-run_fastQC/execution

)
out78339930="${tmpDir}/out.$$" err78339930="${tmpDir}/err.$$"
mkfifo "$out78339930" "$err78339930"
trap 'rm "$out78339930" "$err78339930"' EXIT
touch '/cromwell-executions/assembly_qc/78339930-ab3d-4f8d-b9a3-c4f42da3fab6/call-run_fastQC/execution/stdout' '/cromwell-executions/assembly_qc/78339930-ab3d-4f8d-b9a3-c4f42da3fab6/call-run_fastQC/execution/stderr'
tee '/cromwell-executions/assembly_qc/78339930-ab3d-4f8d-b9a3-c4f42da3fab6/call-run_fastQC/execution/stdout' < "$out78339930" &
tee '/cromwell-executions/assembly_qc/78339930-ab3d-4f8d-b9a3-c4f42da3fab6/call-run_fastQC/execution/stderr' < "$err78339930" >&2 &
(
cd /cromwell-executions/assembly_qc/78339930-ab3d-4f8d-b9a3-c4f42da3fab6/call-run_fastQC/execution


echo "fastQC started"
mkdir fastQC_output
fastqc -o fastQC_output -j /usr/bin/java -f fastq /cromwell-executions/assembly_qc/78339930-ab3d-4f8d-b9a3-c4f42da3fab6/call-run_fastQC/inputs/-233588995/CCI102_S22_R1_001.fastq.gz /cromwell-executions/assembly_qc/78339930-ab3d-4f8d-b9a3-c4f42da3fab6/call-run_fastQC/inputs/-233588995/CCI102_S22_R2_001.fastq.gz
echo "fastQC ended"
)  > "$out78339930" 2> "$err78339930"
echo $? > /cromwell-executions/assembly_qc/78339930-ab3d-4f8d-b9a3-c4f42da3fab6/call-run_fastQC/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/assembly_qc/78339930-ab3d-4f8d-b9a3-c4f42da3fab6/call-run_fastQC/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/assembly_qc/78339930-ab3d-4f8d-b9a3-c4f42da3fab6/call-run_fastQC/execution
sync


)
mv /cromwell-executions/assembly_qc/78339930-ab3d-4f8d-b9a3-c4f42da3fab6/call-run_fastQC/execution/rc.tmp /cromwell-executions/assembly_qc/78339930-ab3d-4f8d-b9a3-c4f42da3fab6/call-run_fastQC/execution/rc
