#!/bin/bash

cd /cromwell-executions/assembly_analysis/bea381fa-11be-4ae3-8b8e-ec36673d8145/call-run_AMRfinderPlus/execution
tmpDir=$(mkdir -p "/cromwell-executions/assembly_analysis/bea381fa-11be-4ae3-8b8e-ec36673d8145/call-run_AMRfinderPlus/tmp.f8e6db0a" && echo "/cromwell-executions/assembly_analysis/bea381fa-11be-4ae3-8b8e-ec36673d8145/call-run_AMRfinderPlus/tmp.f8e6db0a")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/assembly_analysis/bea381fa-11be-4ae3-8b8e-ec36673d8145/call-run_AMRfinderPlus/execution

)
outbea381fa="${tmpDir}/out.$$" errbea381fa="${tmpDir}/err.$$"
mkfifo "$outbea381fa" "$errbea381fa"
trap 'rm "$outbea381fa" "$errbea381fa"' EXIT
touch '/cromwell-executions/assembly_analysis/bea381fa-11be-4ae3-8b8e-ec36673d8145/call-run_AMRfinderPlus/execution/stdout' '/cromwell-executions/assembly_analysis/bea381fa-11be-4ae3-8b8e-ec36673d8145/call-run_AMRfinderPlus/execution/stderr'
tee '/cromwell-executions/assembly_analysis/bea381fa-11be-4ae3-8b8e-ec36673d8145/call-run_AMRfinderPlus/execution/stdout' < "$outbea381fa" &
tee '/cromwell-executions/assembly_analysis/bea381fa-11be-4ae3-8b8e-ec36673d8145/call-run_AMRfinderPlus/execution/stderr' < "$errbea381fa" >&2 &
(
cd /cromwell-executions/assembly_analysis/bea381fa-11be-4ae3-8b8e-ec36673d8145/call-run_AMRfinderPlus/execution


date | tee date
amrfinder --version |tee VERSION
amrfinder --database_version 2>/dev/null | grep "Database version" | sed 's|Database version: ||' | tee DB_VERSION

# When you run 'amrfinder -l' you get a list of the available organisms. Here, the sample's organism is aligned to its match within the database if available. 
    # The list was created with the databse wersion 2024-01-31.1 on April 2nd 2024. 
    # The list will be updated in subsequent versions of this wdl. Users are welcome to update it as well.  
case "Klebsiella pneumoniae" in
    *"Acinetobacter"*"baumannii"*)
        amrfinder_organism="Acinetobacter_baumannii";;
    *"Burkholderia"*"cepacia"*)
        amrfinder_organism="Burkholderia_cepacia";;
    *"Burkholderia"*"pseudomallei"*)
        amrfinder_organism="Burkholderia_pseudomallei";;
    *"Campylobacter"*"coli"* | *"Campylobacter"*"jejuni"*)
        amrfinder_organism="Campylobacter";;
    *"Citrobacter"*"freundii"*)
        amrfinder_organism="Citrobacter_freundii";;
    *"Clostridioides"*"difficile"*)
        amrfinder_organism="Clostridioides_difficile";;
    *"Enterobacter"*"asburiae"*)
        amrfinder_organism="Enterobacter_asburiae";;
    *"Enterobacter"*"asburiae"*)
        amrfinder_organism="Enterobacter_asburiae";;
    *"Enterococcus"*"faecalis"*)
        amrfinder_organism="Enterococcus_faecalis";;
    *"Enterococcus"*"faecium"* | *"Enterococcus"*"hirae"*)
        amrfinder_organism="Enterococcus_faecium";;
    *"Escherichia"* | *"Shigella"*)
        amrfinder_organism="Escherichia";;
    *"Klebsiella"*"oxytoca"*)
        amrfinder_organism="Klebsiella_oxytoca";;
    *"Klebsiella"*"pneumoniae"*)
        amrfinder_organism="Klebsiella_pneumoniae";;
    *"Neisseria"*"gonorrhoeae"*)
        amrfinder_organism="Neisseria_gonorrhoeae";;
    *"Neisseria"*"meningitidis"*)
        amrfinder_organism="Neisseria_meningitidis";;
    *"Pseudomonas"*"aeruginosa"*)
        amrfinder_organism="Pseudomonas_aeruginosa";;
    *"Salmonella"*)
        amrfinder_organism="Salmonella";;
    *"Serratia"*"marcescens"*)
        amrfinder_organism="Serratia_marcescens";;
    *"Staphylococcus"*"aureus"*)
        amrfinder_organism="Staphylococcus_aureus";;
    *"Staphylococcus"*"pseudintermedius"*)
        amrfinder_organism="Staphylococcus_pseudintermedius";;
    *"Streptococcus"*"agalactiae"*)
        amrfinder_organism="Streptococcus_agalactiae";;
    *"Streptococcus"*"pneumoniae"* | *"Streptococcus"*"mitis"*)
        amrfinder_organism="Streptococcus_pneumoniae";;
    *"Streptococcus"*"pyogenes"*)
        amrfinder_organism="Streptococcus_pyogenes";;
    *"Vibrio"*"cholerae"*)
        amrfinder_organism="Vibrio_cholerae";;
    *"Vibrio"*"parahaemolyticus"*)
        amrfinder_organism="Vibrio_parahaemolyticus";;
    *"Vibrio"*"vulnificus"*)
        amrfinder_organism="Vibrio_vulnificus";;
    *)
        echo "amrfinder_organism is not mapped.";;
esac

echo "amrfinder_organism is set to:" ${amrfinder_organism}


# if amrfinder_organism variable is set, use --organism flag, otherwise do not use --organism flag
if [[ -v amrfinder_organism ]] ; then
    echo "Running AMRFinder+ WITH amrfinder_organism."
    # always use --plus flag, others may be left out if param is optional and not supplied 
    amrfinder --plus \
        --organism ${amrfinder_organism} \
        --name CCI86_S6 \
        --nucleotide /cromwell-executions/assembly_analysis/bea381fa-11be-4ae3-8b8e-ec36673d8145/call-run_AMRfinderPlus/inputs/1756935227/CCI86_S6_contigs.fasta.gz \
        -o amrfinderplus_CCI86_S6_all.tsv 

else 
    echo "Running AMRFinder+ WITHOUT amrfinder_organism."
    # always use --plus flag, others may be left out if param is optional and not supplied 
    amrfinder --plus \
        --name CCI86_S6 \
        --nucleotide /cromwell-executions/assembly_analysis/bea381fa-11be-4ae3-8b8e-ec36673d8145/call-run_AMRfinderPlus/inputs/1756935227/CCI86_S6_contigs.fasta.gz \
        -o amrfinderplus_CCI86_S6_all.tsv 
    fi

#TODO what analysis can I do here? Should I even do extra analysis?
)  > "$outbea381fa" 2> "$errbea381fa"
echo $? > /cromwell-executions/assembly_analysis/bea381fa-11be-4ae3-8b8e-ec36673d8145/call-run_AMRfinderPlus/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/assembly_analysis/bea381fa-11be-4ae3-8b8e-ec36673d8145/call-run_AMRfinderPlus/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/assembly_analysis/bea381fa-11be-4ae3-8b8e-ec36673d8145/call-run_AMRfinderPlus/execution
sync


)
mv /cromwell-executions/assembly_analysis/bea381fa-11be-4ae3-8b8e-ec36673d8145/call-run_AMRfinderPlus/execution/rc.tmp /cromwell-executions/assembly_analysis/bea381fa-11be-4ae3-8b8e-ec36673d8145/call-run_AMRfinderPlus/execution/rc
