#!/bin/bash

cd /cromwell-executions/assembly_analysis/83601398-978e-41c6-9f7b-ecc84e75db73/call-run_AMRfinderPlus/execution
tmpDir=$(mkdir -p "/cromwell-executions/assembly_analysis/83601398-978e-41c6-9f7b-ecc84e75db73/call-run_AMRfinderPlus/tmp.a02cc457" && echo "/cromwell-executions/assembly_analysis/83601398-978e-41c6-9f7b-ecc84e75db73/call-run_AMRfinderPlus/tmp.a02cc457")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/assembly_analysis/83601398-978e-41c6-9f7b-ecc84e75db73/call-run_AMRfinderPlus/execution

)
out83601398="${tmpDir}/out.$$" err83601398="${tmpDir}/err.$$"
mkfifo "$out83601398" "$err83601398"
trap 'rm "$out83601398" "$err83601398"' EXIT
touch '/cromwell-executions/assembly_analysis/83601398-978e-41c6-9f7b-ecc84e75db73/call-run_AMRfinderPlus/execution/stdout' '/cromwell-executions/assembly_analysis/83601398-978e-41c6-9f7b-ecc84e75db73/call-run_AMRfinderPlus/execution/stderr'
tee '/cromwell-executions/assembly_analysis/83601398-978e-41c6-9f7b-ecc84e75db73/call-run_AMRfinderPlus/execution/stdout' < "$out83601398" &
tee '/cromwell-executions/assembly_analysis/83601398-978e-41c6-9f7b-ecc84e75db73/call-run_AMRfinderPlus/execution/stderr' < "$err83601398" >&2 &
(
cd /cromwell-executions/assembly_analysis/83601398-978e-41c6-9f7b-ecc84e75db73/call-run_AMRfinderPlus/execution


date | tee date
amrfinder --version |tee AMRFINDER_VERSION
amrfinder --database_version 2>/dev/null | grep "Database version" | sed 's|Database version: ||' | tee AMRFINDER_DB_VERSION

#TODO fix organism mapping
# these are the organisms avaliable for Database version: 2024-01-31.1 when you run 'amrfinder -l' these might need to be manually updated is the data base version is increased
case "Klebsiella pneumoniae" in
    *"Acinetobacter"*"baumannii"*)
        amrfinder_organism="Acinetobacter_baumannii";;
    *"Burkholderia"*"cepacia"*)
        amrfinder_organism="Burkholderia_cepacia";;
    *"Burkholderia"*"pseudomallei"*)
        amrfinder_organism="Burkholderia_pseudomallei";;
    *"Campylobacter"*"coli"* | *"Campylobacter"*"jejuni"*)
        amrfinder_organism="Campylobacter";;
    *"Citrobacter"*"freundii"*)
        amrfinder_organism="Citrobacter_freundii";;
    *"Clostridioides"*"difficile"*)
        amrfinder_organism="Clostridioides_difficile";;
    *"Enterobacter"*"asburiae"*)
        amrfinder_organism="Enterobacter_asburiae";;
    *"Enterobacter"*"asburiae"*)
        amrfinder_organism="Enterobacter_asburiae";;
    *"Enterococcus"*"faecalis"*)
        amrfinder_organism="Enterococcus_faecalis";;
    *"Enterococcus"*"faecium"* | *"Enterococcus"*"hirae"*)
        amrfinder_organism="Enterococcus_faecium";;
    *"Escherichia"* | *"Shigella"*)
        amrfinder_organism="Escherichia";;
    *"Klebsiella"*"oxytoca"*)
        amrfinder_organism="Klebsiella_oxytoca";;
    *"Klebsiella"*"pneumoniae"*)
        amrfinder_organism="Klebsiella_pneumoniae";;
    *"Neisseria"*"gonorrhoeae"*)
        amrfinder_organism="Neisseria_gonorrhoeae";;
    *"Neisseria"*"meningitidis"*)
        amrfinder_organism="Neisseria_meningitidis";;
    *"Pseudomonas"*"aeruginosa"*)
        amrfinder_organism="Pseudomonas_aeruginosa";;
    *"Salmonella"*)
        amrfinder_organism="Salmonella";;
    *"Serratia"*"marcescens"*)
        amrfinder_organism="Serratia_marcescens";;
    *"Staphylococcus"*"aureus"*)
        amrfinder_organism="Staphylococcus_aureus";;
    *"Staphylococcus"*"pseudintermedius"*)
        amrfinder_organism="Staphylococcus_pseudintermedius";;
    *"Streptococcus"*"agalactiae"*)
        amrfinder_organism="Streptococcus_agalactiae";;
    *"Streptococcus"*"pneumoniae"* | *"Streptococcus"*"mitis"*)
        amrfinder_organism="Streptococcus_pneumoniae";;
    *"Streptococcus"*"pyogenes"*)
        amrfinder_organism="Streptococcus_pyogenes";;
    *"Vibrio"*"cholerae"*)
        amrfinder_organism="Vibrio_cholerae";;
    *"Vibrio"*"parahaemolyticus"*)
        amrfinder_organism="Vibrio_parahaemolyticus";;
    *"Vibrio"*"vulnificus"*)
        amrfinder_organism="Vibrio_vulnificus";;
    *)
        echo "Either Gambit predicted taxon is not supported by NCBI-AMRFinderPlus or the user did not supply an organism as input."
        echo "Skipping the use of amrfinder --organism optional parameter.";;
esac

echo "amrfinder_organism is set to:" ${amrfinder_organism}
#TODO Add plus flag
# if amrfinder_organism variable is set, use --organism flag, otherwise do not use --organism flag
if [[ -v amrfinder_organism ]] ; then
# always use --plus flag, others may be left out if param is optional and not supplied 
    amrfinder --plus \
        --organism ${amrfinder_organism} \
        --name CCI102 \
        --nucleotide /cromwell-executions/assembly_analysis/83601398-978e-41c6-9f7b-ecc84e75db73/call-run_AMRfinderPlus/inputs/-1637899042/CCI102_S22_contigs.fasta \
        -o CCI102_amrfinder_all.tsv 
else 
    echo "Either the organism (Klebsiella pneumoniae) is not recognized by NCBI-AMRFinderPlus or the user did not supply an organism as input."
    echo "Skipping the use of amrfinder --organism optional parameter."
    # always use --plus flag, others may be left out if param is optional and not supplied 
    amrfinder --plus \
        --name CCI102 \
        --nucleotide /cromwell-executions/assembly_analysis/83601398-978e-41c6-9f7b-ecc84e75db73/call-run_AMRfinderPlus/inputs/-1637899042/CCI102_S22_contigs.fasta \
        -o CCI102_amrfinder_all.tsv 
    fi
)  > "$out83601398" 2> "$err83601398"
echo $? > /cromwell-executions/assembly_analysis/83601398-978e-41c6-9f7b-ecc84e75db73/call-run_AMRfinderPlus/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/assembly_analysis/83601398-978e-41c6-9f7b-ecc84e75db73/call-run_AMRfinderPlus/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/assembly_analysis/83601398-978e-41c6-9f7b-ecc84e75db73/call-run_AMRfinderPlus/execution
sync


)
mv /cromwell-executions/assembly_analysis/83601398-978e-41c6-9f7b-ecc84e75db73/call-run_AMRfinderPlus/execution/rc.tmp /cromwell-executions/assembly_analysis/83601398-978e-41c6-9f7b-ecc84e75db73/call-run_AMRfinderPlus/execution/rc
